package net.diegoquirino.calculator.ux;// Generated by Selenium IDE

import net.diegoquirino.calculator.ux.pages.InitialPageObject;
import org.junit.jupiter.api.*;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;

@DisplayName("REQ001 - Calcular Desconto de Produto")
public class Req001_ProductDiscountCalculationTest extends BaseTest {

  private InitialPageObject page;

  @BeforeEach
  public void setUp() {
    initialize();
    this.page = new InitialPageObject(driver);
  }

  @AfterEach
  public void tearDown() {
    end();
    this.page = null;
  }

  private String testSteps(String clientType, Integer quantity) {
    return this.page.goToProductsListFromMenu()
            .selectProductFromListCode(2)
            .setClientType(clientType)
            .setQuantity(quantity)
            .submit()
            .getDiscountFactorText();
  }

  @Nested
  @DisplayName("Quando o cliente for do tipo A")
  class ClientA {

    final String CLIENT_A = "A";
    @Test
    @DisplayName("E quantidade entre 1 e 99 ENTAO fator de desconto igual a 0,90 (ou seja, 10% de desconto)")
    public void testWhenClientTypeAQuantityLessThen100() {
      String result = testSteps(CLIENT_A, 1);
      assertThat(result, is("0,90 (ou seja, 10% de desconto)"));
    }
    @Test
    @DisplayName("E quantidade entre 100 e 999 ENTAO fator de desconto igual a 0,95 (ou seja, 5% de desconto)")
    public void testWhenClientTypeAQuantityLessThen1000() {
      String result = testSteps(CLIENT_A, 100);
      assertThat(result, is("0,95 (ou seja, 5% de desconto)"));
    }
    @Test
    @DisplayName("E quantidade a partir de 1000 ENTAO fator de desconto igual a 1,00 (ou seja, 0% de desconto)")
    public void testWhenClientTypeAQuantityGreaterThen1000() {
      String result = testSteps(CLIENT_A, 1000);
      assertThat(result, is("1,00 (ou seja, 0% de desconto)"));
    }

  }

  @Nested
  @DisplayName("Quando o cliente for do tipo B")
  class ClientB {

    final String CLIENT_B = "B";
    @Test
    @DisplayName("E quantidade entre 1 e 99 ENTAO fator de desconto igual a 0,85 (ou seja, 15% de desconto)")
    public void testWhenClientTypeBQuantityLessThen100() {
      String result = testSteps(CLIENT_B, 1);
      assertThat(result, is("0,85 (ou seja, 15% de desconto)"));
    }
    @Test
    @DisplayName("E quantidade entre 100 e 999 ENTAO fator de desconto igual a 0,90 (ou seja, 10% de desconto)")
    public void testWhenClientTypeAQuantityLessThen1000() {
      String result = testSteps(CLIENT_B, 100);
      assertThat(result, is("0,90 (ou seja, 10% de desconto)"));
    }
    @Test
    @DisplayName("E quantidade a partir de 1000 ENTAO fator de desconto igual a 0,95 (ou seja, 5% de desconto)")
    public void testWhenClientTypeAQuantityGreaterThen1000() {
      String result = testSteps(CLIENT_B, 1000);
      assertThat(result, is("0,95 (ou seja, 5% de desconto)"));
    }

  }

  @Nested
  @DisplayName("Quando o cliente for do tipo C")
  class ClientC {

    final String CLIENT_C = "C";
    @Test
    @DisplayName("E quantidade entre 1 e 99 ENTAO fator de desconto igual a 0,80 (ou seja, 20% de desconto)")
    public void testWhenClientTypeBQuantityLessThen100() {
      String result = testSteps(CLIENT_C, 1);
      assertThat(result, is("0,80 (ou seja, 20% de desconto)"));
    }
    @Test
    @DisplayName("E quantidade entre 100 e 999 ENTAO fator de desconto igual a 0,95 (ou seja, 5% de desconto)")
    public void testWhenClientTypeAQuantityLessThen1000() {
      String result = testSteps(CLIENT_C, 100);
      assertThat(result, is("0,85 (ou seja, 15% de desconto)"));
    }
    @Test
    @DisplayName("E quantidade a partir de 1000 ENTAO fator de desconto igual a 0,90 (ou seja, 10% de desconto)")
    public void testWhenClientTypeAQuantityGreaterThen1000() {
      String result = testSteps(CLIENT_C, 1000);
      assertThat(result, is("0,90 (ou seja, 10% de desconto)"));
    }
    @Test
    @DisplayName("E quantidade com valor invalido ENTAO mensagem de erro")
    public void testWhenClientTypeAnyQuantityLessEqualZero() {
      String result = testSteps(CLIENT_C, -2);
      assertThat(result, is("A quantidade informada deve ser maior ou igual a 01 (um)!"));
    }
    @Test
    @DisplayName("E quantidade vazio ENTAO mensagem de erro")
    public void testWhenClientTypeAnyWithoutQuantity() {
      String result = testSteps(CLIENT_C, null);
      assertThat(result, is("A quantidade informada deve ser maior ou igual a 01 (um)!"));
    }
  }
}
